## TODO:

* copy all the stuff done in ccle for task 1
* do the task 2:

Look at the instructions on the mail 

(Buffa link that she looked at in class: https://portal.gdc.cancer.gov/analysis_page?app=Downloads), selected WGS, somatic structural variation, vcf, Manta, primary, solid tissue

In [1]:
import pandas as pd
import numpy as np
from sklearn.manifold import TSNE
import seaborn as sns
import umap
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from collections import Counter

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import xgboost as xgb

/opt/anaconda3/envs/bio_env/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Import data

In [ ]:
rna = pd.read_csv("data_tcga/data_mrna_seq_fpkm.txt", sep="\t").T.reset_index()
rna.columns = rna.iloc[0]
rna = rna[1:] 
rna

,Hugo_Symbol,TSPAN6,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,...,AP000230.1,RP11-80H18.4,RP13-297E16.4,LL0YNC03-29C1.1,RP13-297E16.5,BX649553.1,BX649553.3,BX649553.4,RN7SL355P,MIR3690
1,SP89389,65.515874,0.046881,63.315522,2.222857,2.565836,2.167233,1.265078,34.199996,4.974365,...,0.147707,0.24506,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,SP21193,93.507754,0.655002,23.608843,1.933762,1.861716,3.873639,3.268175,23.050032,4.019948,...,0.011216,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,SP13206,15.155525,0.0,42.136192,2.318698,2.87044,4.286835,9.066806,32.926751,3.909932,...,0.02706,0.179581,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,SP103623,9.75167,0.188735,14.507132,2.342167,0.454312,13.098299,26.108567,25.074303,0.682193,...,0.241574,1.479853,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,SP32742,16.04885,0.014542,45.302557,4.373694,4.125029,4.316576,16.914069,15.602162,8.076706,...,0.04009,0.15203,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1206,SP16269,0.007476,0.0,23.290497,6.46653,6.384945,235.016264,0.013622,5.548667,13.125604,...,0.0,0.432225,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1207,SP122676,9.736614,0.062405,31.444337,1.072155,1.207673,5.166039,5.904768,61.047477,2.502007,...,0.0,0.733968,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1208,SP88776,29.283034,0.0,23.118048,3.699246,0.539174,0.450032,0.403973,25.097563,6.154079,...,0.751576,1.280037,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1209,SP64546,28.04515,0.026696,51.549932,1.989817,1.556905,1.276369,9.101945,15.649566,6.412556,...,0.087614,0.232576,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1210,SP21057,62.010994,0.405261,30.790944,3.313589,1.757992,1.44242,1.695267,28.040086,6.889364,...,0.076611,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
mutation_type = pd.read_csv("data_tcga/mutations.txt", sep="\t")
mutation_type

               STUDY_ID SAMPLE_ID         TP53
0     pancan_pcawg_2020  SP107436           WT
1     pancan_pcawg_2020  SP107435           WT
2     pancan_pcawg_2020  SP107407           WT
3     pancan_pcawg_2020  SP107406           WT
4     pancan_pcawg_2020  SP107405           WT
...                 ...       ...          ...
2678  pancan_pcawg_2020    SP8891  X187_splice
2679  pancan_pcawg_2020   SP88776           WT
2680  pancan_pcawg_2020   SP88757           WT
2681  pancan_pcawg_2020   SP88593           WT
2682  pancan_pcawg_2020   SP88322           WT

[2683 rows x 3 columns]

In [ ]:
types_of_mutation = mutation_type["TP53"]
(Counter(types_of_mutation))

Counter({'WT': 1781,
         'R273H': 33,
         'R175H': 27,
         'R248Q': 25,
         'R282W': 23,
         'Y220C': 20,
         'R213*': 18,
         'R248W': 18,
         'X126_splice': 17,
         'R273C': 15,
         'G245S': 11,
         'R306*': 10,
         'R342*': 9,
         'K132N': 8,
         'R196*': 8,
         'H193R': 8,
         'X187_splice': 7,
         'X331_splice': 7,
         'H179R': 7,
         'X125_splice': 7,
         'X307_splice': 7,
         'M237I': 6,
         'I195T': 6,
         'X261_splice': 6,
         'S241F': 6,
         'Y163C': 6,
         'Y205C': 6,
         'Q331*': 6,
         'R337C': 6,
         'X225_splice': 5,
         'H214R': 5,
         'Q192*': 5,
         'V272M': 5,
         'S241C': 5,
         'C238F': 5,
         'G262V': 5,
         'R209Kfs*6': 5,
         'Q317*': 5,
         'V157F': 5,
         'X224_splice': 4,
         'E286K': 4,
         'W91*': 4,
         'X332_splice': 4,
         'A161T': 4,
         'Y234*': 4,
         'R337L': 4,
         'S241P': 4,
         'Y236C': 4,
         'P151S': 4,
         'C176Y': 4,
         'D281N': 4,
         'G266V': 4,
         'G244C': 3,
         'Q144*': 3,
         'G245D': 3,
         'E294*': 3,
         'P278R': 3,
         'K132R': 3,
         'V172F': 3,
         'W146*': 3,
         'R273L': 3,
         'C124Wfs*25': 3,
         'R249G': 3,
         'Y234C': 3,
         'C275Y': 3,
         'V173M': 3,
         'S215G': 3,
         'C242F': 3,
         'C176F': 3,
         'R175G': 3,
         'I195F': 3,
         'L130F': 3,
         'C141Y': 3,
         'N239*': 3,
         'P153Afs*28': 3,
         'P151A': 3,
         'R280K': 3,
         'H193L': 3,
         'C242Afs*5': 3,
         'S215R': 3,
         'V216M': 2,
         'A276G': 2,
         'F134C': 2,
         'R213Q': 2,
         'C135F': 2,
         'H179Q': 2,
         'R158P': 2,
         'E343Gfs*2': 2,
         'C135W': 2,
         'G279E': 2,
         'C135R': 2,
         'E294Sfs*51': 2,
         'C242S': 2,
         'L111P': 2,
         'L194R': 2,
         'G245V': 2,
         'S215I': 2,
         'F212Sfs*3': 2,
         'V157_R158del': 2,
         'C135Y': 2,
         'E204*': 2,
         'F134L': 2,
         'S215N': 2,
         'H179Y': 2,
         'S183*': 2,
         'I255del': 2,
         'G266E': 2,
         'G245C': 2,
         'G266R': 2,
         'P278T': 2,
         'Y234H': 2,
         'W53*': 2,
         'E285K': 2,
         'R249M': 2,
         'N239D': 2,
         'R249S': 2,
         'H178Pfs*3': 2,
         'E171*': 2,
         'N310Tfs*35': 2,
         'V274A': 2,
         'Q104*': 2,
         'V173L': 2,
         'Q136E': 2,
         'E221*': 2,
         'H179L': 2,
         'Y236*': 2,
         'X10_splice': 2,
         'A159V': 2,
         'I162N': 2,
         'V218Cfs*29': 2,
         'K132E': 2,
         'X33_splice': 2,
         'P190L': 2,
         'Y236H': 2,
         'C275Lfs*67': 1,
         'L257V': 1,
         'V217Wfs*30': 1,
         'L201*': 1,
         'V157G': 1,
         'S241Pfs*6': 1,
         'P98Afs*51': 1,
         'G108Vfs*15': 1,
         'D48N': 1,
         'N30I': 1,
         'S241Y': 1,
         'I255F': 1,
         'R280Kfs*26': 1,
         'H168P': 1,
         'E339Rfs*6': 1,
         'P85Lfs*38': 1,
         'F113G': 1,
         'R249Sfs*96': 1,
         'C176G': 1,
         'S240Mfs*25': 1,
         'S96Lfs*27': 1,
         'D148_S149insYTP': 1,
         'K291*': 1,
         'Y205Wfs*41': 1,
         'V218del': 1,
         'C124*': 1,
         'L130H': 1,
         'A86Lfs*38': 1,
         'T304Efs*39': 1,
         'A138V': 1,
         'A138P': 1,
         'H168R': 1,
         'C238Y': 1,
         'Q167*': 1,
         'R213L': 1,
         'V143M': 1,
         'I232F': 1,
         'C124G': 1,
         'P177Tfs*69': 1,
         'F113V': 1,
         'Q136*': 1,
         'A276D': 1,
         'Y107Tfs*16': 1,
         'N239Tfs*8': 1,
         'C229Lfs*12': 1,
         'T18Hfs*26': 1,
         'P219Wfs*30': 1,
         'E198*': 1,
         'Q331Rfs*14': 1,
         'C176F G245V': 1,
         'R249K': 1,
         'T81Rfs*41': 1,
         'T284Rfs*21': 1,
         'P222Gfs*4': 1,
         'K132N H179L': 1,
         'R273H C135F': 1,
         'F270C': 1,
         'E285Rfs*54': 1,
         'X32_splice': 1,
         'S106R': 1,
         'I251L': 1,
         'F113I': 1,
         'P58Rfs*6': 1,
         'S227_C229del': 1,
         'L257P': 1,
         'Y236S': 1,
         'L93Pfs*56': 1,
         'X186_splice': 1,
         'R337C R273L': 1,
         'I255T': 1,
         'D281E': 1,
         'S241_M246delinsL': 1,
         'E258D': 1,
         'S95Ifs*54': 1,
         'S241A': 1,
         'F328Sfs*17': 1,
         'G302Rfs*4': 1,
         'R181C': 1,
         'R273H D208G': 1,
         'R342* R181H': 1,
         'H179R G244S': 1,
         'P153Afs*16 X222_splice': 1,
         'C176S': 1,
         'H193Y': 1,
         'V197M': 1,
         'T253Nfs*11': 1,
         'S90Pfs*33': 1,
         'R342Pfs*5': 1,
         'Q192_H193delinsHY': 1,
         'G262del': 1,
         'V73Wfs*50': 1,
         'Y205H': 1,
         'H115Afs*34': 1,
         'E204del': 1,
         'Y220_E221delins*': 1,
         'W91Cfs*32': 1,
         'Y236del': 1,
         'T150Hfs*20': 1,
         'T140Dfs*9': 1,
         'S240G': 1,
         '*394Ifs*27': 1,
         'X224_splice C229W': 1,
         'P278S': 1,
         'K132*': 1,
         'C135F X125_splice': 1,
         'P75Gfs*66': 1,
         'P152Rfs*18': 1,
         'V216L': 1,
         'E336Sfs*9': 1,
         'C229Yfs*10': 1,
         'E346*': 1,
         'V272L': 1,
         'N268I': 1,
         'M246V G245R': 1,
         'D393Rfs*78': 1,
         'L145Q': 1,
         'C238R': 1,
         'C176W': 1,
         'Y236N': 1,
         'V197G': 1,
         'R213* Y205C': 1,
         'C275W': 1,
         'C141W': 1,
         'R337H C176F': 1,
         'H178Q': 1,
         'K292*': 1,
         'E336Afs*10': 1,
         'G262Vfs*83': 1,
         'Y126D': 1,
         'F109V': 1,
         'E339* X125_splice': 1,
         'R213* R282W': 1,
         'R248W L114*': 1,
         'R110Wfs*12': 1,
         'P278S Y205*': 1,
         'R175H R283P': 1,
         'H168L': 1,
         'T256Hfs*8': 1,
         'K101*': 1,
         'V274dup': 1,
         'V73Rfs*76 Q136P': 1,
         'C238F R156P': 1,
         'H193L P177_C182del': 1,
         'R273H V272L': 1,
         'H179R M237V': 1,
         'K139Nfs*9': 1,
         'R267P': 1,
         'R248Q S127Y': 1,
         'G108Afs*39 G108Pfs*39': 1,
         'G266E T312I': 1,
         'R196Efs*51': 1,
         'D184H E271Q': 1,
         'P152L': 1,
         'L111Ifs*8': 1,
         'E343Afs*3': 1,
         'L145R': 1,
         'P301Qfs*44': 1,
         'F109C': 1,
         'R213* K132T': 1,
         'E271K': 1,
         'R213* S94*': 1,
         'E258G': 1,
         'P142Lfs*28': 1,
         'A159P': 1,
         'C242Y': 1,
         'Y220C V272G': 1,
         'S303Afs*42': 1,
         'K132T': 1,
         'H193Lfs*54': 1,
         'G325Efs*20': 1,
         'H179del': 1,
         'R181H': 1,
         'L201Ffs*8': 1,
         'S149Ifs*32': 1,
         'C141_L145del': 1,
         'R196P': 1,
         'R156P': 1,
         'Y205N': 1,
         'L257Q': 1,
         'E51Gfs*6': 1,
         'P278H': 1,
         'F134V': 1,
         'V274G': 1,
         'T150Afs*16': 1,
         'M237K': 1,
         'L348_E349delinsF*': 1,
         'R248G': 1,
         'P72Rfs*76': 1,
         'T284Rfs*21 V218dup': 1,
         'K139N': 1,
         'V172D': 1,
         'Q38*': 1,
         'G105C': 1,
         'H193D': 1,
         'A86Cfs*63': 1,
         'I195S': 1,
         'L252_T253delinsP': 1,
         'L265Tfs*7': 1,
         'A347_L348dup': 1,
         'E68*': 1,
         'R158L': 1,
         'S315Lfs*30': 1,
         'I162dup': 1,
         'M246I': 1,
         'Q192_H193del': 1,
         'G244S': 1,
         'R282H': 1,
         'R248P': 1,
         'Y205F': 1,
         'G105D': 1,
         'K292Gfs*52': 1,
         'Q165Afs*6': 1,
         'R249Gfs*96': 1,
         'V122Dfs*26': 1,
         'E224D': 1,
         'R280I': 1,
         'K139Rfs*31': 1,
         'F54Sfs*69': 1,
         'R110L': 1,
         'P190S': 1,
         'E204Sfs*43': 1,
         'E349*': 1,
         'Y163*': 1,
         'A161S': 1,
         'R110Sfs*14': 1,
         'T155P': 1,
         'L35Cfs*9': 1,
         'T284Kfs*61': 1,
         'K120E': 1,
         'R290C A159V': 1,
         'S127P': 1,
         'I251F': 1,
         'G226Rfs*23': 1,
         'N131Tfs*39': 1,
         'R335Qfs*2': 1,
         'P151H': 1,
         'Y205S': 1,
         'R267W': 1,
         'Q167Afs*13': 1,
         'V217G': 1,
         'P177_C182del': 1,
         'K132Q': 1,
         'A63Cfs*57': 1,
         'I254T': 1,
         'D259Y': 1,
         'Q144P': 1,
         'F212V': 1,
         'R174N': 1,
         'Q317Efs*16': 1,
         'Y220N': 1,
         'R280G': 1,
         'V173A': 1,
         'Q317Sfs*28': 1,
         'R267L': 1,
         'V173E': 1,
         'R213P': 1,
         'Y163N': 1,
         'T253N I254V': 1,
         'C135*': 1,
         'Y103Tfs*20': 1,
         'H178Pfs*2': 1,
         'R156del': 1,
         'C277F': 1,
         'Q38Kfs*6': 1,
         'R273S': 1,
         'V157_P177del': 1,
         'P128_L130del': 1,
         'H178D': 1,
         'Q167Hfs*3': 1,
         'C135R C141Y': 1,
         'Y220H': 1,
         'R273C R158C S90Pfs*33': 1,
         'R249W': 1,
         'C277dup': 1,
         'T211Lfs*36': 1})

## Task 2

### Look at Sean datasets

In [12]:
import gzip
import os

file_path = 'data_tcga/tcga(sean)/mrna_mutation_data/218cbd80-c866-48b9-90d6-d0a5210fd96d/579a3ebc-d38d-4029-a05c-d3e8ea2549d8.wxs.aliquot_ensemble_masked.maf.gz'

with gzip.open(file_path, 'rt') as f:
    lines = f.readlines()
    print(f"First 10 lines of {file_path}:")
    for line in lines:
        print(line.strip())

First 10 lines of data_tcga/tcga(sean)/mrna_mutation_data/218cbd80-c866-48b9-90d6-d0a5210fd96d/579a3ebc-d38d-4029-a05c-d3e8ea2549d8.wxs.aliquot_ensemble_masked.maf.gz:
#version gdc-1.0.0
#annotation.spec gdc-2.0.0-aliquot-merged-masked
#contigs chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY,chrM
#sort.order BarcodesAndCoordinate
#filedate 20220519
#normal.aliquot 0ffd9ad1-6643-42ff-af29-13389bfb1364
#tumor.aliquot 49fb101d-f242-4abf-bf85-6a8c3ced711d
Hugo_Symbol	Entrez_Gene_Id	Center	NCBI_Build	Chromosome	Start_Position	End_Position	Strand	Variant_Classification	Variant_Type	Reference_Allele	Tumor_Seq_Allele1	Tumor_Seq_Allele2	dbSNP_RS	dbSNP_Val_Status	Tumor_Sample_Barcode	Matched_Norm_Sample_Barcode	Match_Norm_Seq_Allele1	Match_Norm_Seq_Allele2	Tumor_Validation_Allele1	Tumor_Validation_Allele2	Match_Norm_Validation_Allele1	Match_Norm_Validation_Allele2	Verification_Status	Validation_Status	Mutation_Status	Sequencing_Phase	Sequence_Source	Validation_Method	Score	BAM_File	Sequencer	Tumor_Sample_UUID	Matched_Norm_Sample_UUID	HGVSc	HGVSp	HGVSp_Short	Transcript_ID	Exon_Number	t_depth	t_ref_count	t_alt_count	n_depth	n_ref_count	n_alt_count	all_effects	Allele	Gene	Feature	Feature_type	One_Consequence	Consequence	cDNA_position	CDS_position	Protein_position	Amino_acids	Codons	Existing_variation	DISTANCE	TRANSCRIPT_STRAND	SYMBOL	SYMBOL_SOURCE	HGNC_ID	BIOTYPE	CANONICAL	CCDS	ENSP	SWISSPROT	TREMBL	UNIPARC	UNIPROT_ISOFORM	RefSeq	MANE	APPRIS	FLAGS	SIFT	PolyPhen	EXON	INTRON	DOMAINS	1000G_AF	1000G_AFR_AF	1000G_AMR_AF	1000G_EAS_AF	1000G_EUR_AF	1000G_SAS_AF	ESP_AA_AF	ESP_EA_AF	gnomAD_AF	gnomAD_AFR_AF	gnomAD_AMR_AF	gnomAD_ASJ_AF	gnomAD_EAS_AF	gnomAD_FIN_AF	gnomAD_NFE_AF	gnomAD_OTH_AF	gnomAD_SAS_AF	MAX_AF	MAX_AF_POPS	gnomAD_non_cancer_AF	gnomAD_non_cancer_AFR_AF	gnomAD_non_cancer_AMI_AF	gnomAD_non_cancer_AMR_AF	gnomAD_non_cancer_ASJ_AF	gnomAD_non_cancer_EAS_AF	gnomAD_non_cancer_FIN_AF	gnomAD_non_cancer_MID_AF	gnomAD_non_cancer_NFE_AF	gnomAD_non_cancer_OTH_AF	gnomAD_non_cancer_SAS_AF	gnomAD_non_cancer_MAX_AF_adj	gnomAD_non_cancer_MAX_AF_POPS_adj	CLIN_SIG	SOMATIC	PUBMED	TRANSCRIPTION_FACTORS	MOTIF_NAME	MOTIF_POS	HIGH_INF_POS	MOTIF_SCORE_CHANGE	miRNA	IMPACT	PICK	VARIANT_CLASS	TSL	HGVS_OFFSET	PHENO	GENE_PHENO	CONTEXT	tumor_bam_uuid	normal_bam_uuid	case_id	GDC_FILTER	COSMIC	hotspot	RNA_Support	RNA_depth	RNA_ref_count	RNA_alt_count	callers
IKBKE	9641	WUGSC	GRCh38	chr1	206474921	206474921	+	Silent	SNP	G	G	A			TCGA-XX-A899-01A-11D-A36J-09	TCGA-XX-A899-10A-01D-A36M-09									Somatic							49fb101d-f242-4abf-bf85-6a8c3ced711d	0ffd9ad1-6643-42ff-af29-13389bfb1364	c.285G>A	p.Leu95=	p.L95=	ENST00000581977	5/22	52	46	6	52			IKBKE,synonymous_variant,p.L95=,ENST00000581977,NM_014002.4,c.285G>A,LOW,YES,,,1;IKBKE,synonymous_variant,p.L95=,ENST00000578328,NM_001193322.2,c.285G>A,LOW,,,,1;IKBKE,synonymous_variant,p.L10=,ENST00000584998,NM_001193321.2,c.30G>A,LOW,,,,1;IKBKE,synonymous_variant,p.L95=,ENST00000579827,,c.285G>A,LOW,,,,1;IKBKE,synonymous_variant,p.L95=,ENST00000605726,,c.285G>A,LOW,,,,1;MIR6769B,downstream_gene_variant,,ENST00000622159,,,MODIFIER,YES,,,1;IKBKE,non_coding_transcript_exon_variant,,ENST00000605818,,n.630G>A,MODIFIER,,,,1	A	ENSG00000263528	ENST00000581977	Transcript	synonymous_variant	synonymous_variant	630/3240	285/2151	95/716	L	ctG/ctA	COSV100898121;COSV100898272		1	IKBKE	HGNC	HGNC:14552	protein_coding	YES	CCDS30996.1	ENSP00000464030	Q14164.200		UPI0000033727	Q14164-1	NM_014002.4	NM_014002.4	P1				5/22		Gene3D:1.10.510.10;Pfam:PF00069;PROSITE_profiles:PS50011;PANTHER:PTHR22969;PANTHER:PTHR22969:SF10;SMART:SM00220;Superfamily:SSF56112																																		1;1								LOW	1	SNV	1		1;1		CTGCTGAGTGT	f74293a0-f4b4-49da-937f-db43c68d9062	a7447bac-36b2-44c3-86a0-6e52a550ef34	f89588e9-ca73-4465-a7fb-7246edb45e3a			N	Unknown				muse;mutect2;varscan2
NCKAP5	344148	WUGSC	GRCh38	chr2	132783591	132783591	+	Missense_Mutation	SNP	C	C	T			TCGA-XX-A899-01A-11D-A36J-09	TCGA-XX-A899-10A-01D-A36M-09									Somatic							49fb101d-f242-4abf-bf85-6a8c3ced711d	0ffd9ad1-6643-42ff-af29-13389bfb1364	c.3220G>A	p.Glu1074Lys	p.E1074K	ENST00000409261	14/20	87	77	10	106			NCKAP5,missense_variant,p.E1074K,ENST00000409261,NM_207363.3,c.3220G>A,MODERATE,YES,tolerated(0.22),benign(0.382),-1;NCKAP5,missense_variant,p.E1074K,ENST00000317721,,c.3220G>A,MODERATE,,tolerated(0.23),probably_damaging(0.92),-1;NCKAP5,intron_variant,,ENST00000405974,,c.1092+6432G>A,MODIFIER,,,,-1;NCKAP5,intron_variant,,ENST00000409213,NM_207481.4,c.1092+6432G>A,MODIFIER,,,,-1;NCKAP5,upstream_gene_variant,,ENST00000473859,,,MODIFIER,,,,-1;AC010974.2,intron_variant,,ENST00000651100,,n.458-31010C>T,MODIFIER,YES,,,1	T	ENSG00000176771	ENST00000409261	Transcript	missense_variant	missense_variant	3597/7608	3220/5730	1074/1909	E/K	Gag/Aag	COSV100490649		-1	NCKAP5	HGNC	HGNC:29847	protein_coding	YES	CCDS46418.1	ENSP00000387128	O14513.127		UPI0000E07A3F	O14513-1	NM_207363.3	NM_207363.3	P4		tolerated(0.22)	benign(0.382)	14/20		PANTHER:PTHR21740;PANTHER:PTHR21740:SF0;MobiDB_lite:mobidb-lite;MobiDB_lite:mobidb-lite																				6.762879820598755e-06	2.4333299734280445e-05	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0				1								MODERATE	1	SNV	5		1		TGGCTCATGGG	f74293a0-f4b4-49da-937f-db43c68d9062	a7447bac-36b2-44c3-86a0-6e52a550ef34	f89588e9-ca73-4465-a7fb-7246edb45e3a			N	Unknown				muse;varscan2
PIK3CA	5290	WUGSC	GRCh38	chr3	179199073	179199073	+	Missense_Mutation	SNP	T	T	C	rs1560137208		TCGA-XX-A899-01A-11D-A36J-09	TCGA-XX-A899-10A-01D-A36M-09									Somatic							49fb101d-f242-4abf-bf85-6a8c3ced711d	0ffd9ad1-6643-42ff-af29-13389bfb1364	c.248T>C	p.Phe83Ser	p.F83S	ENST00000263967	2/21	131	103	28	134			PIK3CA,missense_variant,p.F83S,ENST00000263967,NM_006218.4,c.248T>C,MODERATE,YES,deleterious(0.02),benign(0.06),1;PIK3CA,missense_variant,p.F83S,ENST00000643187,,c.248T>C,MODERATE,,deleterious(0.01),benign(0.283),1;PIK3CA,missense_variant,p.F83S,ENST00000468036,,c.248T>C,MODERATE,,tolerated(0.33),benign(0.06),1;PIK3CA,downstream_gene_variant,,ENST00000477735,,,MODIFIER,,,,1;PIK3CA,missense_variant,p.F83S,ENST00000675786,,c.248T>C,MODERATE,,deleterious(0),possibly_damaging(0.47),1;PIK3CA,non_coding_transcript_exon_variant,,ENST00000675467,,n.3055T>C,MODIFIER,,,,1;PIK3CA,upstream_gene_variant,,ENST00000674534,,,MODIFIER,,,,1	C	ENSG00000121879	ENST00000263967	Transcript	missense_variant	missense_variant	571/9259	248/3207	83/1068	F/S	tTt/tCt	rs1560137208;COSV55924440;COSV55950009		1	PIK3CA	HGNC	HGNC:8975	protein_coding	YES	CCDS43171.1	ENSP00000263967	P42336.214		UPI000013D494		NM_006218.4	NM_006218.4	P1		deleterious(0.02)	benign(0.06)	2/21		PDB-ENSP_mappings:2rd0.A;PDB-ENSP_mappings:3hhm.A;PDB-ENSP_mappings:3hiz.A;PDB-ENSP_mappings:4jps.A;PDB-ENSP_mappings:4l1b.A;PDB-ENSP_mappings:4l23.A;PDB-ENSP_mappings:4l2y.A;PDB-ENSP_mappings:4ovu.A;PDB-ENSP_mappings:4ovv.A;PDB-ENSP_mappings:4waf.A;PDB-ENSP_mappings:4ykn.A;PDB-ENSP_mappings:4zop.A;PDB-ENSP_mappings:5dxh.A;PDB-ENSP_mappings:5dxh.D;PDB-ENSP_mappings:5fi4.A;PDB-ENSP_mappings:5itd.A;PDB-ENSP_mappings:5sw8.A;PDB-ENSP_mappings:5swg.A;PDB-ENSP_mappings:5swo.A;PDB-ENSP_mappings:5swp.A;PDB-ENSP_mappings:5swr.A;PDB-ENSP_mappings:5swt.A;PDB-ENSP_mappings:5sx8.A;PDB-ENSP_mappings:5sx9.A;PDB-ENSP_mappings:5sxa.A;PDB-ENSP_mappings:5sxb.A;PDB-ENSP_mappings:5sxc.A;PDB-ENSP_mappings:5sxd.A;PDB-ENSP_mappings:5sxe.A;PDB-ENSP_mappings:5sxf.A;PDB-ENSP_mappings:5sxi.A;PDB-ENSP_mappings:5sxj.A;PDB-ENSP_mappings:5sxk.A;PDB-ENSP_mappings:5uk8.A;PDB-ENSP_mappings:5ukj.A;PDB-ENSP_mappings:5ul1.A;PDB-ENSP_mappings:5xgh.A;PDB-ENSP_mappings:5xgi.A;PDB-ENSP_mappings:5xgj.A;PDB-ENSP_mappings:6nct.A;PROSITE_profiles:PS51544;PANTHER:PTHR10048;PANTHER:PTHR10048:SF103;Pfam:PF02192;Gene3D:3.10.20.90;SMART:SM00143																																	pathogenic	0;1;1	29446767							MODERATE	1	SNV	2		1;1;1	1	ATTTTTTGATG	f74293a0-f4b4-49da-937f-db43c68d9062	a7447bac-36b2-44c3-86a0-6e52a550ef34	f89588e9-ca73-4465-a7fb-7246edb45e3a		COSM5346971	N	Unknown				muse;mutect2;varscan2
CLDN1	9076	WUGSC	GRCh38	chr3	190322110	190322110	+	Missense_Mutation	SNP	A	A	G			TCGA-XX-A899-01A-11D-A36J-09	TCGA-XX-A899-10A-01D-A36M-09									Somatic							49fb101d-f242-4abf-bf85-6a8c3ced711d	0ffd9ad1-6643-42ff-af29-13389bfb1364	c.97T>C	p.Tyr33His	p.Y33H	ENST00000295522	1/4	66	56	9	73			CLDN1,missense_variant,p.Y33H,ENST00000295522,NM_021101.5,c.97T>C,MODERATE,YES,deleterious(0),possibly_damaging(0.722),-1;CLDN16,upstream_gene_variant,,ENST00000468220,,,MODIFIER,,,,1	G	ENSG00000163347	ENST00000295522	Transcript	missense_variant	missense_variant	337/3446	97/636	33/211	Y/H	Tac/Cac	COSV99790524		-1	CLDN1	HGNC	HGNC:2032	protein_coding	YES	CCDS3295.1	ENSP00000295522	O95832.174	A5JSJ9.119	UPI0000046D1E		NM_021101.5	NM_021101.5	P1		deleterious(0)	possibly_damaging(0.722)	1/4		Gene3D:1.20.140.150;Pfam:PF00822;PANTHER:PTHR12002;PANTHER:PTHR12002:SF92																																		1								MODERATE	1	SNV	1		1	1	GGAGTAAATCC	f74293a0-f4b4-49da-937f-db43c68d9062	a7447bac-36b2-44c3-86a0-6e52a550ef34	f89588e9-ca73-4465-a7fb-7246edb45e3a			N	Unknown				muse;mutect2;varscan2
DCK	1633	WUGSC	GRCh38	chr4	71026729	71026729	+	Missense_Mutation	SNP	G	G	T			TCGA-XX-A899-01A-11D-A36J-09	TCGA-XX-A899-10A-01D-A36M-09									Somatic							49fb101d-f242-4abf-bf85-6a8c3ced711d	0ffd9ad1-6643-42ff-af29-13389bfb1364	c.730G>T	p.Asp244Tyr	p.D244Y	ENST00000286648	6/7	140	118	22	164			DCK,missense_variant,p.D244Y,ENST00000504952,,c.730G>T,MODERATE,YES,deleterious(0),benign(0.106),1;DCK,missense_variant,p.D244Y,ENST00000286648,NM_000788.3,c.730G>T,MODERATE,,deleterious(0),benign(0.026),1;DCK,3_prime_UTR_variant,,ENST00000504730,,c.*14G>T,MODIFIER,,,,1;MOB1B,downstream_gene_variant,,ENST00000511449,,,MODIFIER,,,,1;DCK,3_prime_UTR_variant,,ENST00000503359,,c.*674G>T,MODIFIER,,,,1;DCK,non_coding_transcript_exon_variant,,ENST00000509764,,n.113G>T,MODIFIER,,,,1	T	ENSG00000156136	ENST00000286648	Transcript	missense_variant	missense_variant	917/2506	730/783	244/260	D/Y	Gac/Tac	COSV99709141		1	DCK	HGNC	HGNC:2704	protein_coding		CCDS3548.1	ENSP00000286648	P27707.180	F5CTF3.56	UPI0000128FC6		NM_000788.3	NM_000788.3	P1		deleterious(0)	benign(0.026)	6/7		PDB-ENSP_mappings:1p5z.B;PDB-ENSP_mappings:1p60.A;PDB-ENSP_mappings:1p60.B;PDB-ENSP_mappings:1p61.B;PDB-ENSP_mappings:1p62.B;PDB-ENSP_mappings:2a2z.A;PDB-ENSP_mappings:2a2z.B;PDB-ENSP_mappings:2a2z.C;PDB-ENSP_mappings:2a2z.D;PDB-ENSP_mappings:2a30.A;PDB-ENSP_mappings:2a30.B;PDB-ENSP_mappings:2a30.C;PDB-ENSP_mappings:2a30.D;PDB-ENSP_mappings:2a7q.A;PDB-ENSP_mappings:2no0.A;PDB-ENSP_mappings:2no0.B;PDB-ENSP_mappings:2no1.A;PDB-ENSP_mappings:2no1.B;PDB-ENSP_mappings:2no6.A;PDB-ENSP_mappings:2no6.B;PDB-ENSP_mappings:2no7.A;PDB-ENSP_mappings:2no7.B;PDB-ENSP_mappings:2no9.A;PDB-ENSP_mappings:2no9.B;PDB-ENSP_mappings:2noa.A;PDB-ENSP_mappings:2noa.B;PDB-ENSP_mappings:2qrn.A;PDB-ENSP_mappings:2qrn.B;PDB-ENSP_mappings:2qrn.C;PDB-ENSP_mappings:2qrn.D;PDB-ENSP_mappings:2qro.A;PDB-ENSP_mappings:2qro.B;PDB-ENSP_mappings:2qro.C;PDB-ENSP_mappings:2qro.D;PDB-ENSP_mappings:2zi3.A;PDB-ENSP_mappings:2zi3.B;PDB-ENSP_mappings:2zi4.A;PDB-ENSP_mappings:2zi5.A;PDB-ENSP_mappings:2zi5.B;PDB-ENSP_mappings:2zi5.C;PDB-ENSP_mappings:2zi5.D;PDB-ENSP_mappings:2zi6.A;PDB-ENSP_mappings:2zi6.B;PDB-ENSP_mappings:2zi6.C;PDB-ENSP_mappings:2zi6.D;PDB-ENSP_mappings:2zi7.A;PDB-ENSP_mappings:2zi7.B;PDB-ENSP_mappings:2zi9.A;PDB-ENSP_mappings:2zi9.B;PDB-ENSP_mappings:2zia.A;PDB-ENSP_mappings:2zia.B;Gene3D:3.40.50.300;PDB-ENSP_mappings:3hp1.A;PDB-ENSP_mappings:3ipx.A;PDB-ENSP_mappings:3ipy.A;PDB-ENSP_mappings:3ipy.B;PDB-ENSP_mappings:3kfx.A;PDB-ENSP_mappings:3kfx.B;PDB-ENSP_mappings:3mjr.A;PDB-ENSP_mappings:3mjr.B;PDB-ENSP_mappings:3mjr.C;PDB-ENSP_mappings:3mjr.D;PDB-ENSP_mappings:3qej.A;PDB-ENSP_mappings:3qej.B;PDB-ENSP_mappings:3qen.A;PDB-ENSP_mappings:3qen.B;PDB-ENSP_mappings:3qeo.A;PDB-ENSP_mappings:3qeo.B;PDB-ENSP_mappings:4jlj.A;PDB-ENSP_mappings:4jlj.B;PDB-ENSP_mappings:4jlk.A;PDB-ENSP_mappings:4jlk.B;PDB-ENSP_mappings:4jlm.A;PDB-ENSP_mappings:4jlm.B;PDB-ENSP_mappings:4jln.A;PDB-ENSP_mappings:4jln.B;PDB-ENSP_mappings:4kcg.A;PDB-ENSP_mappings:4kcg.B;PDB-ENSP_mappings:4l5b.A;PDB-ENSP_mappings:4l5b.B;PDB-ENSP_mappings:4q18.A;PDB-ENSP_mappings:4q18.B;PDB-ENSP_mappings:4q19.A;PDB-ENSP_mappings:4q19.B;PDB-ENSP_mappings:4q1a.A;PDB-ENSP_mappings:4q1a.B;PDB-ENSP_mappings:4q1b.A;PDB-ENSP_mappings:4q1b.B;PDB-ENSP_mappings:4q1c.A;PDB-ENSP_mappings:4q1c.B;PDB-ENSP_mappings:4q1d.A;PDB-ENSP_mappings:4q1d.B;PDB-ENSP_mappings:4q1e.A;PDB-ENSP_mappings:4q1e.B;PDB-ENSP_mappings:4q1f.A;PDB-ENSP_mappings:4q1f.B;PDB-ENSP_mappings:5mqj.A;PDB-ENSP_mappings:5mqj.B;PDB-ENSP_mappings:5mqj.C;PDB-ENSP_mappings:5mqj.D;PDB-ENSP_mappings:5mql.A;PDB-ENSP_mappings:5mql.B;PDB-ENSP_mappings:5mql.C;PDB-ENSP_mappings:5mql.D;PDB-ENSP_mappings:5mqt.A;PDB-ENSP_mappings:5mqt.B;PDB-ENSP_mappings:5mqt.C;PDB-ENSP_mappings:5mqt.D;Pfam:PF01712;PIRSF:PIRSF000705;PANTHER:PTHR10513;PANTHER:PTHR10513:SF19;Superfamily:SSF52540;CDD:cd01673																																		1								MODERATE		SNV	1		1		TTAAAGACAAA	f74293a0-f4b4-49da-937f-db43c68d9062	a7447bac-36b2-44c3-86a0-6e52a550ef34	f89588e9-ca73-4465-a7fb-7246edb45e3a			N	Unknown				muse;mutect2;varscan2
TNXB	7148	WUGSC	GRCh38	chr6	32085979	32085979	+	Missense_Mutation	SNP	C	C	G			TCGA-XX-A899-01A-11D-A36J-09	TCGA-XX-A899-10A-01D-A36M-09									Somatic							49fb101d-f242-4abf-bf85-6a8c3ced711d	0ffd9ad1-6643-42ff-af29-13389bfb1364	c.3660G>C	p.Glu1220Asp	p.E1220D	ENST00000647633	8/45	123	110	13	142			TNXB,missense_variant,p.E1220D,ENST00000647633,,c.3660G>C,MODERATE,YES,tolerated(0.54),possibly_damaging(0.535),-1;TNXB,missense_variant,p.E973D,ENST00000375244,,c.2919G>C,MODERATE,,tolerated(0.25),benign(0.248),-1;TNXB,missense_variant,p.E973D,ENST00000644971,NM_019105.8&NM_001365276.2,c.2919G>C,MODERATE,,tolerated(0.25),benign(0.248),-1;TNXB,missense_variant,p.E1060D,ENST00000613214,,c.3180G>C,MODERATE,,tolerated(0.34),benign(0.074),-1	G	ENSG00000168477	ENST00000647633	Transcript	missense_variant	missense_variant	3820/13831	3660/13476	1220/4491	E/D	gaG/gaC	COSV100926028		-1	TNXB	HGNC	HGNC:11976	protein_coding	YES		ENSP00000497649		A0A3B3ISX9.10	UPI000E6F2261				P1		tolerated(0.54)	possibly_damaging(0.535)	8/45		PROSITE_profiles:PS50853;PANTHER:PTHR46708;PANTHER:PTHR46708:SF3;SMART:SM00060;Superfamily:SSF49265																																		1								MODERATE	1	SNV			1	1	CCTGTCTCATC	f74293a0-f4b4-49da-937f-db43c68d9062	a7447bac-36b2-44c3-86a0-6e52a550ef34	f89588e9-ca73-4465-a7fb-7246edb45e3a			N	Unknown				muse;mutect2;varscan2
FAM135A	57579	WUGSC	GRCh38	chr6	70524011	70524011	+	Missense_Mutation	SNP	C	C	T			TCGA-XX-A899-01A-11D-A36J-09	TCGA-XX-A899-10A-01D-A36M-09									Somatic							49fb101d-f242-4abf-bf85-6a8c3ced711d	0ffd9ad1-6643-42ff-af29-13389bfb1364	c.1148C>T	p.Ser383Phe	p.S383F	ENST00000370479	12/20	49	37	12	55			FAM135A,missense_variant,p.S383F,ENST00000418814,NM_001351607.1&NM_001330999.2&NM_001331004.2&NM_001351602.1&NM_001330996.2&NM_001331005.2&NM_001162529.3,c.1148C>T,MODERATE,YES,deleterious(0),probably_damaging(0.994),1;FAM135A,missense_variant,p.S383F,ENST00000370479,NM_001351599.1&NM_001351600.1,c.1148C>T,MODERATE,,deleterious(0),probably_damaging(0.994),1;FAM135A,missense_variant,p.S366F,ENST00000457062,NM_001351609.1&NM_001351608.1&NM_020819.4,c.1097C>T,MODERATE,,deleterious(0),probably_damaging(0.98),1;FAM135A,missense_variant,p.S383F,ENST00000505868,,c.1148C>T,MODERATE,,deleterious(0),probably_damaging(0.999),1;FAM135A,missense_variant,p.S383F,ENST00000361499,NM_001330998.2&NM_001105531.2&NM_001331003.2&NM_001331002.2&NM_001330997.2&NM_001331000.2&NM_001331001.2,c.1148C>T,MODERATE,,deleterious(0.01),probably_damaging(0.98),1;FAM135A,missense_variant,p.S383F,ENST00000505769,NM_001331006.2&NM_001330995.2,c.1148C>T,MODERATE,,deleterious(0.01),probably_damaging(0.956),1;FAM135A,missense_variant,p.S383F,ENST00000515323,,c.1148C>T,MODERATE,,deleterious(0.01),probably_damaging(0.994),1;FAM135A,3_prime_UTR_variant,,ENST00000194672,,c.*648C>T,MODIFIER,,,,1;FAM135A,non_coding_transcript_exon_variant,,ENST00000393299,,n.1183C>T,MODIFIER,,,,1	T	ENSG00000082269	ENST00000370479	Transcript	missense_variant	missense_variant	1281/5930	1148/4548	383/1515	S/F	tCc/tTc	COSV52058570		1	FAM135A	HGNC	HGNC:21084	protein_coding		CCDS55028.1	ENSP00000359510	Q9P2D6.131		UPI000004A0FF	Q9P2D6-1	NM_001351599.1;NM_001351600.1		P4		deleterious(0)	probably_damaging(0.994)	12/20		PANTHER:PTHR12482;PANTHER:PTHR12482:SF40																																		1								MODERATE		SNV	1		1		TACTTCCTTCT	f74293a0-f4b4-49da-937f-db43c68d9062	a7447bac-36b2-44c3-86a0-6e52a550ef34	f89588e9-ca73-4465-a7fb-7246edb45e3a		COSM5585149;COSM5585150	N	Unknown				muse;mutect2;varscan2
MAPK15	225689	WUGSC	GRCh38	chr8	143720241	143720241	+	Missense_Mutation	SNP	C	C	T			TCGA-XX-A899-01A-11D-A36J-09	TCGA-XX-A899-10A-01D-A36M-09									Somatic							49fb101d-f242-4abf-bf85-6a8c3ced711d	0ffd9ad1-6643-42ff-af29-13389bfb1364	c.733C>T	p.Leu245Phe	p.L245F	ENST00000338033	8/14	43	35	8	64			MAPK15,missense_variant,p.L245F,ENST00000338033,NM_139021.3,c.733C>T,MODERATE,YES,tolerated(0.09),benign(0.199),1;MAPK15,missense_variant,p.L262F,ENST00000395107,,c.784C>T,MODERATE,,deleterious(0.04),benign(0.083),1;MAPK15,intron_variant,,ENST00000395108,,c.722-307C>T,MODIFIER,,,,1;FAM83H,downstream_gene_variant,,ENST00000388913,NM_198488.5,,MODIFIER,,,,-1;FAM83H,downstream_gene_variant,,ENST00000650760,,,MODIFIER,YES,,,-1;MAPK15,non_coding_transcript_exon_variant,,ENST00000484654,,n.822C>T,MODIFIER,,,,1;MAPK15,non_coding_transcript_exon_variant,,ENST00000533830,,n.50C>T,MODIFIER,,,,1;FAM83H,downstream_gene_variant,,ENST00000395103,,,MODIFIER,,,,-1;MAPK15,upstream_gene_variant,,ENST00000461928,,,MODIFIER,,,,1;MAPK15,downstream_gene_variant,,ENST00000475376,,,MODIFIER,,,,1;MAPK15,upstream_gene_variant,,ENST00000528175,,,MODIFIER,,,,1;AC105219.1,upstream_gene_variant,,ENST00000527908,,,MODIFIER,YES,,,-1	T	ENSG00000181085	ENST00000338033	Transcript	missense_variant	missense_variant	762/1871	733/1635	245/544	L/F	Ctc/Ttc	COSV100567746		1	MAPK15	HGNC	HGNC:24667	protein_coding	YES	CCDS6409.2	ENSP00000337691	Q8TD08.151		UPI00000496E7	Q8TD08-1	NM_139021.3	NM_139021.3	P1		tolerated(0.09)	benign(0.199)	8/14		PROSITE_profiles:PS50011;CDD:cd07852;PANTHER:PTHR24055;PANTHER:PTHR24055:SF178;Pfam:PF00069;Gene3D:1.10.510.10;Gene3D:3.30.200.20;Superfamily:SSF56112																																		1								MODERATE	1	SNV	1		1		TGGCTCTCGGC	f74293a0-f4b4-49da-937f-db43c68d9062	a7447bac-36b2-44c3-86a0-6e52a550ef34	f89588e9-ca73-4465-a7fb-7246edb45e3a			N	Unknown				muse;mutect2;varscan2

In [11]:
len(lines)

42

In [ ]:
# make lines into pandas dataframe
import pandas as pd
import gzip
import os

['PIK3CA\t5290\tWUGSC\tGRCh38\tchr3\t179199073\t179199073\t+\tMissense_Mutation\tSNP\tT\tT\tC\trs1560137208\t\tTCGA-XX-A899-01A-11D-A36J-09\tTCGA-XX-A899-10A-01D-A36M-09\t\t\t\t\t\t\t\t\tSomatic\t\t\t\t\t\t\t49fb101d-f242-4abf-bf85-6a8c3ced711d\t0ffd9ad1-6643-42ff-af29-13389bfb1364\tc.248T>C\tp.Phe83Ser\tp.F83S\tENST00000263967\t2/21\t131\t103\t28\t134\t\t\tPIK3CA,missense_variant,p.F83S,ENST00000263967,NM_006218.4,c.248T>C,MODERATE,YES,deleterious(0.02),benign(0.06),1;PIK3CA,missense_variant,p.F83S,ENST00000643187,,c.248T>C,MODERATE,,deleterious(0.01),benign(0.283),1;PIK3CA,missense_variant,p.F83S,ENST00000468036,,c.248T>C,MODERATE,,tolerated(0.33),benign(0.06),1;PIK3CA,downstream_gene_variant,,ENST00000477735,,,MODIFIER,,,,1;PIK3CA,missense_variant,p.F83S,ENST00000675786,,c.248T>C,MODERATE,,deleterious(0),possibly_damaging(0.47),1;PIK3CA,non_coding_transcript_exon_variant,,ENST00000675467,,n.3055T>C,MODIFIER,,,,1;PIK3CA,upstream_gene_variant,,ENST00000674534,,,MODIFIER,,,,1\tC\tENSG00000121879\tENST00000263967\tTranscript\tmissense_variant\tmissense_variant\t571/9259\t248/3207\t83/1068\tF/S\ttTt/tCt\trs1560137208;COSV55924440;COSV55950009\t\t1\tPIK3CA\tHGNC\tHGNC:8975\tprotein_coding\tYES\tCCDS43171.1\tENSP00000263967\tP42336.214\t\tUPI000013D494\t\tNM_006218.4\tNM_006218.4\tP1\t\tdeleterious(0.02)\tbenign(0.06)\t2/21\t\tPDB-ENSP_mappings:2rd0.A;PDB-ENSP_mappings:3hhm.A;PDB-ENSP_mappings:3hiz.A;PDB-ENSP_mappings:4jps.A;PDB-ENSP_mappings:4l1b.A;PDB-ENSP_mappings:4l23.A;PDB-ENSP_mappings:4l2y.A;PDB-ENSP_mappings:4ovu.A;PDB-ENSP_mappings:4ovv.A;PDB-ENSP_mappings:4waf.A;PDB-ENSP_mappings:4ykn.A;PDB-ENSP_mappings:4zop.A;PDB-ENSP_mappings:5dxh.A;PDB-ENSP_mappings:5dxh.D;PDB-ENSP_mappings:5fi4.A;PDB-ENSP_mappings:5itd.A;PDB-ENSP_mappings:5sw8.A;PDB-ENSP_mappings:5swg.A;PDB-ENSP_mappings:5swo.A;PDB-ENSP_mappings:5swp.A;PDB-ENSP_mappings:5swr.A;PDB-ENSP_mappings:5swt.A;PDB-ENSP_mappings:5sx8.A;PDB-ENSP_mappings:5sx9.A;PDB-ENSP_mappings:5sxa.A;PDB-ENSP_mappings:5sxb.A;PDB-ENSP_mappings:5sxc.A;PDB-ENSP_mappings:5sxd.A;PDB-ENSP_mappings:5sxe.A;PDB-ENSP_mappings:5sxf.A;PDB-ENSP_mappings:5sxi.A;PDB-ENSP_mappings:5sxj.A;PDB-ENSP_mappings:5sxk.A;PDB-ENSP_mappings:5uk8.A;PDB-ENSP_mappings:5ukj.A;PDB-ENSP_mappings:5ul1.A;PDB-ENSP_mappings:5xgh.A;PDB-ENSP_mappings:5xgi.A;PDB-ENSP_mappings:5xgj.A;PDB-ENSP_mappings:6nct.A;PROSITE_profiles:PS51544;PANTHER:PTHR10048;PANTHER:PTHR10048:SF103;Pfam:PF02192;Gene3D:3.10.20.90;SMART:SM00143\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tpathogenic\t0;1;1\t29446767\t\t\t\t\t\t\tMODERATE\t1\tSNV\t2\t\t1;1;1\t1\tATTTTTTGATG\tf74293a0-f4b4-49da-937f-db43c68d9062\ta7447bac-36b2-44c3-86a0-6e52a550ef34\tf89588e9-ca73-4465-a7fb-7246edb45e3a\t\tCOSM5346971\tN\tUnknown\t\t\t\tmuse;mutect2;varscan2\n', 'CLDN1\t9076\tWUGSC\tGRCh38\tchr3\t190322110\t190322110\t+\tMissense_Mutation\tSNP\tA\tA\tG\t\t\tTCGA-XX-A899-01A-11D-A36J-09\tTCGA-XX-A899-10A-01D-A36M-09\t\t\t\t\t\t\t\t\tSomatic\t\t\t\t\t\t\t49fb101d-f242-4abf-bf85-6a8c3ced711d\t0ffd9ad1-6643-42ff-af29-13389bfb1364\tc.97T>C\tp.Tyr33His\tp.Y33H\tENST00000295522\t1/4\t66\t56\t9\t73\t\t\tCLDN1,missense_variant,p.Y33H,ENST00000295522,NM_021101.5,c.97T>C,MODERATE,YES,deleterious(0),possibly_damaging(0.722),-1;CLDN16,upstream_gene_variant,,ENST00000468220,,,MODIFIER,,,,1\tG\tENSG00000163347\tENST00000295522\tTranscript\tmissense_variant\tmissense_variant\t337/3446\t97/636\t33/211\tY/H\tTac/Cac\tCOSV99790524\t\t-1\tCLDN1\tHGNC\tHGNC:2032\tprotein_coding\tYES\tCCDS3295.1\tENSP00000295522\tO95832.174\tA5JSJ9.119\tUPI0000046D1E\t\tNM_021101.5\tNM_021101.5\tP1\t\tdeleterious(0)\tpossibly_damaging(0.722)\t1/4\t\tGene3D:1.20.140.150;Pfam:PF00822;PANTHER:PTHR12002;PANTHER:PTHR12002:SF92\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t1\t\t\t\t\t\t\t\tMODERATE\t1\tSNV\t1\t\t1\t1\tGGAGTAAATCC\tf74293a0-f4b4-49da-937f-db43c68d9062\ta7447bac-36b2-44c3-86a0-6e52a550ef34\tf89588e9-ca73-4465-a7fb-7246edb45e3a\t\t\tN\tUnknown\t\t\t\tmuse;mutect2;varscan2\n', 'DCK\t1633\tWUGSC\tGRCh38\tchr4\t71026729\t71026729\t+\tMissense_Mutation\tSNP\tG\tG\tT\t\t\tTCGA-XX-A899-01A-11D-A36J-09\tTCGA-XX-A899-10A-01D-A36M-09\t\t\t\t\t\t\t\t\tSomatic\t\t\t\t\t\t\t49fb101d-f242-4abf-bf85-6a8c3ced711d\t0ffd9ad1-6643-42ff-af29-13389bfb1364\tc.730G>T\tp.Asp244Tyr\tp.D244Y\tENST00000286648\t6/7\t140\t118\t22\t164\t\t\tDCK,missense_variant,p.D244Y,ENST00000504952,,c.730G>T,MODERATE,YES,deleterious(0),benign(0.106),1;DCK,missense_variant,p.D244Y,ENST00000286648,NM_000788.3,c.730G>T,MODERATE,,deleterious(0),benign(0.026),1;DCK,3_prime_UTR_variant,,ENST00000504730,,c.*14G>T,MODIFIER,,,,1;MOB1B,downstream_gene_variant,,ENST00000511449,,,MODIFIER,,,,1;DCK,3_prime_UTR_variant,,ENST00000503359,,c.*674G>T,MODIFIER,,,,1;DCK,non_coding_transcript_exon_variant,,ENST00000509764,,n.113G>T,MODIFIER,,,,1\tT\tENSG00000156136\tENST00000286648\tTranscript\tmissense_variant\tmissense_variant\t917/2506\t730/783\t244/260\tD/Y\tGac/Tac\tCOSV99709141\t\t1\tDCK\tHGNC\tHGNC:2704\tprotein_coding\t\tCCDS3548.1\tENSP00000286648\tP27707.180\tF5CTF3.56\tUPI0000128FC6\t\tNM_000788.3\tNM_000788.3\tP1\t\tdeleterious(0)\tbenign(0.026)\t6/7\t\tPDB-ENSP_mappings:1p5z.B;PDB-ENSP_mappings:1p60.A;PDB-ENSP_mappings:1p60.B;PDB-ENSP_mappings:1p61.B;PDB-ENSP_mappings:1p62.B;PDB-ENSP_mappings:2a2z.A;PDB-ENSP_mappings:2a2z.B;PDB-ENSP_mappings:2a2z.C;PDB-ENSP_mappings:2a2z.D;PDB-ENSP_mappings:2a30.A;PDB-ENSP_mappings:2a30.B;PDB-ENSP_mappings:2a30.C;PDB-ENSP_mappings:2a30.D;PDB-ENSP_mappings:2a7q.A;PDB-ENSP_mappings:2no0.A;PDB-ENSP_mappings:2no0.B;PDB-ENSP_mappings:2no1.A;PDB-ENSP_mappings:2no1.B;PDB-ENSP_mappings:2no6.A;PDB-ENSP_mappings:2no6.B;PDB-ENSP_mappings:2no7.A;PDB-ENSP_mappings:2no7.B;PDB-ENSP_mappings:2no9.A;PDB-ENSP_mappings:2no9.B;PDB-ENSP_mappings:2noa.A;PDB-ENSP_mappings:2noa.B;PDB-ENSP_mappings:2qrn.A;PDB-ENSP_mappings:2qrn.B;PDB-ENSP_mappings:2qrn.C;PDB-ENSP_mappings:2qrn.D;PDB-ENSP_mappings:2qro.A;PDB-ENSP_mappings:2qro.B;PDB-ENSP_mappings:2qro.C;PDB-ENSP_mappings:2qro.D;PDB-ENSP_mappings:2zi3.A;PDB-ENSP_mappings:2zi3.B;PDB-ENSP_mappings:2zi4.A;PDB-ENSP_mappings:2zi5.A;PDB-ENSP_mappings:2zi5.B;PDB-ENSP_mappings:2zi5.C;PDB-ENSP_mappings:2zi5.D;PDB-ENSP_mappings:2zi6.A;PDB-ENSP_mappings:2zi6.B;PDB-ENSP_mappings:2zi6.C;PDB-ENSP_mappings:2zi6.D;PDB-ENSP_mappings:2zi7.A;PDB-ENSP_mappings:2zi7.B;PDB-ENSP_mappings:2zi9.A;PDB-ENSP_mappings:2zi9.B;PDB-ENSP_mappings:2zia.A;PDB-ENSP_mappings:2zia.B;Gene3D:3.40.50.300;PDB-ENSP_mappings:3hp1.A;PDB-ENSP_mappings:3ipx.A;PDB-ENSP_mappings:3ipy.A;PDB-ENSP_mappings:3ipy.B;PDB-ENSP_mappings:3kfx.A;PDB-ENSP_mappings:3kfx.B;PDB-ENSP_mappings:3mjr.A;PDB-ENSP_mappings:3mjr.B;PDB-ENSP_mappings:3mjr.C;PDB-ENSP_mappings:3mjr.D;PDB-ENSP_mappings:3qej.A;PDB-ENSP_mappings:3qej.B;PDB-ENSP_mappings:3qen.A;PDB-ENSP_mappings:3qen.B;PDB-ENSP_mappings:3qeo.A;PDB-ENSP_mappings:3qeo.B;PDB-ENSP_mappings:4jlj.A;PDB-ENSP_mappings:4jlj.B;PDB-ENSP_mappings:4jlk.A;PDB-ENSP_mappings:4jlk.B;PDB-ENSP_mappings:4jlm.A;PDB-ENSP_mappings:4jlm.B;PDB-ENSP_mappings:4jln.A;PDB-ENSP_mappings:4jln.B;PDB-ENSP_mappings:4kcg.A;PDB-ENSP_mappings:4kcg.B;PDB-ENSP_mappings:4l5b.A;PDB-ENSP_mappings:4l5b.B;PDB-ENSP_mappings:4q18.A;PDB-ENSP_mappings:4q18.B;PDB-ENSP_mappings:4q19.A;PDB-ENSP_mappings:4q19.B;PDB-ENSP_mappings:4q1a.A;PDB-ENSP_mappings:4q1a.B;PDB-ENSP_mappings:4q1b.A;PDB-ENSP_mappings:4q1b.B;PDB-ENSP_mappings:4q1c.A;PDB-ENSP_mappings:4q1c.B;PDB-ENSP_mappings:4q1d.A;PDB-ENSP_mappings:4q1d.B;PDB-ENSP_mappings:4q1e.A;PDB-ENSP_mappings:4q1e.B;PDB-ENSP_mappings:4q1f.A;PDB-ENSP_mappings:4q1f.B;PDB-ENSP_mappings:5mqj.A;PDB-ENSP_mappings:5mqj.B;PDB-ENSP_mappings:5mqj.C;PDB-ENSP_mappings:5mqj.D;PDB-ENSP_mappings:5mql.A;PDB-ENSP_mappings:5mql.B;PDB-ENSP_mappings:5mql.C;PDB-ENSP_mappings:5mql.D;PDB-ENSP_mappings:5mqt.A;PDB-ENSP_mappings:5mqt.B;PDB-ENSP_mappings:5mqt.C;PDB-ENSP_mappings:5mqt.D;Pfam:PF01712;PIRSF:PIRSF000705;PANTHER:PTHR10513;PANTHER:PTHR10513:SF19;Superfamily:SSF52540;CDD:cd01673\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t1\t\t\t\t\t\t\t\tMODERATE\t\tSNV\t1\t\t1\t\tTTAAAGACAAA\tf74293a0-f4b4-49da-937f-db43c68d9062\ta7447bac-36b2-44c3-86a0-6e52a550ef34\tf89588e9-ca73-4465-a7fb-7246edb45e3a\t\t\tN\tUnknown\t\t\t\tmuse;mutect2;varscan2\n', 'TNXB\t7148\tWUGSC\tGRCh38\tchr6\t32085979\t32085979\t+\tMissense_Mutation\tSNP\tC\tC\tG\t\t\tTCGA-XX-A899-01A-11D-A36J-09\tTCGA-XX-A899-10A-01D-A36M-09\t\t\t\t\t\t\t\t\tSomatic\t\t\t\t\t\t\t49fb101d-f242-4abf-bf85-6a8c3ced711d\t0ffd9ad1-6643-42ff-af29-13389bfb1364\tc.3660G>C\tp.Glu1220Asp\tp.E1220D\tENST00000647633\t8/45\t123\t110\t13\t142\t\t\tTNXB,missense_variant,p.E1220D,ENST00000647633,,c.3660G>C,MODERATE,YES,tolerated(0.54),possibly_damaging(0.535),-1;TNXB,missense_variant,p.E973D,ENST00000375244,,c.2919G>C,MODERATE,,tolerated(0.25),benign(0.248),-1;TNXB,missense_variant,p.E973D,ENST00000644971,NM_019105.8&NM_001365276.2,c.2919G>C,MODERATE,,tolerated(0.25),benign(0.248),-1;TNXB,missense_variant,p.E1060D,ENST00000613214,,c.3180G>C,MODERATE,,tolerated(0.34),benign(0.074),-1\tG\tENSG00000168477\tENST00000647633\tTranscript\tmissense_variant\tmissense_variant\t3820/13831\t3660/13476\t1220/4491\tE/D\tgaG/gaC\tCOSV100926028\t\t-1\tTNXB\tHGNC\tHGNC:11976\tprotein_coding\tYES\t\tENSP00000497649\t\tA0A3B3ISX9.10\tUPI000E6F2261\t\t\t\tP1\t\ttolerated(0.54)\tpossibly_damaging(0.535)\t8/45\t\tPROSITE_profiles:PS50853;PANTHER:PTHR46708;PANTHER:PTHR46708:SF3;SMART:SM00060;Superfamily:SSF49265\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t1\t\t\t\t\t\t\t\tMODERATE\t1\tSNV\t\t\t1\t1\tCCTGTCTCATC\tf74293a0-f4b4-49da-937f-db43c68d9062\ta7447bac-36b2-44c3-86a0-6e52a550ef34\tf89588e9-ca73-4465-a7fb-7246edb45e3a\t\t\tN\tUnknown\t\t\t\tmuse;mutect2;varscan2\n', 'FAM135A\t57579\tWUGSC\tGRCh38\tchr6\t70524011\t70524011\t+\tMissense_Mutation\tSNP\tC\tC\tT\t\t\tTCGA-XX-A899-01A-11D-A36J-09\tTCGA-XX-A899-10A-01D-A36M-09\t\t\t\t\t\t\t\t\tSomatic\t\t\t\t\t\t\t49fb101d-f242-4abf-bf85-6a8c3ced711d\t0ffd9ad1-6643-42ff-af29-13389bfb1364\tc.1148C>T\tp.Ser383Phe\tp.S383F\tENST00000370479\t12/20\t49\t37\t12\t55\t\t\tFAM135A,missense_variant,p.S383F,ENST00000418814,NM_001351607.1&NM_001330999.2&NM_001331004.2&NM_001351602.1&NM_001330996.2&NM_001331005.2&NM_001162529.3,c.1148C>T,MODERATE,YES,deleterious(0),probably_damaging(0.994),1;FAM135A,missense_variant,p.S383F,ENST00000370479,NM_001351599.1&NM_001351600.1,c.1148C>T,MODERATE,,deleterious(0),probably_damaging(0.994),1;FAM135A,missense_variant,p.S366F,ENST00000457062,NM_001351609.1&NM_001351608.1&NM_020819.4,c.1097C>T,MODERATE,,deleterious(0),probably_damaging(0.98),1;FAM135A,missense_variant,p.S383F,ENST00000505868,,c.1148C>T,MODERATE,,deleterious(0),probably_damaging(0.999),1;FAM135A,missense_variant,p.S383F,ENST00000361499,NM_001330998.2&NM_001105531.2&NM_001331003.2&NM_001331002.2&NM_001330997.2&NM_001331000.2&NM_001331001.2,c.1148C>T,MODERATE,,deleterious(0.01),probably_damaging(0.98),1;FAM135A,missense_variant,p.S383F,ENST00000505769,NM_001331006.2&NM_001330995.2,c.1148C>T,MODERATE,,deleterious(0.01),probably_damaging(0.956),1;FAM135A,missense_variant,p.S383F,ENST00000515323,,c.1148C>T,MODERATE,,deleterious(0.01),probably_damaging(0.994),1;FAM135A,3_prime_UTR_variant,,ENST00000194672,,c.*648C>T,MODIFIER,,,,1;FAM135A,non_coding_transcript_exon_variant,,ENST00000393299,,n.1183C>T,MODIFIER,,,,1\tT\tENSG00000082269\tENST00000370479\tTranscript\tmissense_variant\tmissense_variant\t1281/5930\t1148/4548\t383/1515\tS/F\ttCc/tTc\tCOSV52058570\t\t1\tFAM135A\tHGNC\tHGNC:21084\tprotein_coding\t\tCCDS55028.1\tENSP00000359510\tQ9P2D6.131\t\tUPI000004A0FF\tQ9P2D6-1\tNM_001351599.1;NM_001351600.1\t\tP4\t\tdeleterious(0)\tprobably_damaging(0.994)\t12/20\t\tPANTHER:PTHR12482;PANTHER:PTHR12482:SF40\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t1\t\t\t\t\t\t\t\tMODERATE\t\tSNV\t1\t\t1\t\tTACTTCCTTCT\tf74293a0-f4b4-49da-937f-db43c68d9062\ta7447bac-36b2-44c3-86a0-6e52a550ef34\tf89588e9-ca73-4465-a7fb-7246edb45e3a\t\tCOSM5585149;COSM5585150\tN\tUnknown\t\t\t\tmuse;mutect2;varscan2\n', 'MAPK15\t225689\tWUGSC\tGRCh38\tchr8\t143720241\t143720241\t+\tMissense_Mutation\tSNP\tC\tC\tT\t\t\tTCGA-XX-A899-01A-11D-A36J-09\tTCGA-XX-A899-10A-01D-A36M-09\t\t\t\t\t\t\t\t\tSomatic\t\t\t\t\t\t\t49fb101d-f242-4abf-bf85-6a8c3ced711d\t0ffd9ad1-6643-42ff-af29-13389bfb1364\tc.733C>T\tp.Leu245Phe\tp.L245F\tENST00000338033\t8/14\t43\t35\t8\t64\t\t\tMAPK15,missense_variant,p.L245F,ENST00000338033,NM_139021.3,c.733C>T,MODERATE,YES,tolerated(0.09),benign(0.199),1;MAPK15,missense_variant,p.L262F,ENST00000395107,,c.784C>T,MODERATE,,deleterious(0.04),benign(0.083),1;MAPK15,intron_variant,,ENST00000395108,,c.722-307C>T,MODIFIER,,,,1;FAM83H,downstream_gene_variant,,ENST00000388913,NM_198488.5,,MODIFIER,,,,-1;FAM83H,downstream_gene_variant,,ENST00000650760,,,MODIFIER,YES,,,-1;MAPK15,non_coding_transcript_exon_variant,,ENST00000484654,,n.822C>T,MODIFIER,,,,1;MAPK15,non_coding_transcript_exon_variant,,ENST00000533830,,n.50C>T,MODIFIER,,,,1;FAM83H,downstream_gene_variant,,ENST00000395103,,,MODIFIER,,,,-1;MAPK15,upstream_gene_variant,,ENST00000461928,,,MODIFIER,,,,1;MAPK15,downstream_gene_variant,,ENST00000475376,,,MODIFIER,,,,1;MAPK15,upstream_gene_variant,,ENST00000528175,,,MODIFIER,,,,1;AC105219.1,upstream_gene_variant,,ENST00000527908,,,MODIFIER,YES,,,-1\tT\tENSG00000181085\tENST00000338033\tTranscript\tmissense_variant\tmissense_variant\t762/1871\t733/1635\t245/544\tL/F\tCtc/Ttc\tCOSV100567746\t\t1\tMAPK15\tHGNC\tHGNC:24667\tprotein_coding\tYES\tCCDS6409.2\tENSP00000337691\tQ8TD08.151\t\tUPI00000496E7\tQ8TD08-1\tNM_139021.3\tNM_139021.3\tP1\t\ttolerated(0.09)\tbenign(0.199)\t8/14\t\tPROSITE_profiles:PS50011;CDD:cd07852;PANTHER:PTHR24055;PANTHER:PTHR24055:SF178;Pfam:PF00069;Gene3D:1.10.510.10;Gene3D:3.30.200.20;Superfamily:SSF56112\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t1\t\t\t\t\t\t\t\tMODERATE\t1\tSNV\t1\t\t1\t\tTGGCTCTCGGC\tf74293a0-f4b4-49da-937f-db43c68d9062\ta7447bac-36b2-44c3-86a0-6e52a550ef34\tf89588e9-ca73-4465-a7fb-7246edb45e3a\t\t\tN\tUnknown\t\t\t\tmuse;mutect2;varscan2\n', 'MARK2\t2011\tWUGSC\tGRCh38\tchr11\t63900796\t63900796\t+\tMissense_Mutation\tSNP\tG\tG\tA\trs199684279\t\tTCGA-XX-A899-01A-11D-A36J-09\tTCGA-XX-A899-10A-01D-A36M-09\t\t\t\t\t\t\t\t\tSomatic\t\t\t\t\t\t\t49fb101d-f242-4abf-bf85-6a8c3ced711d\t0ffd9ad1-6643-42ff-af29-13389bfb1364\tc.905G>A\tp.Arg302Gln\tp.R302Q\tENST00000402010\t10/19\t46\t40\t5\t42\t\t\tMARK2,missense_variant,p.R302Q,ENST00000377810,,c.905G>A,MODERATE,,deleterious(0.01),probably_damaging(0.969),1;MARK2,missense_variant,p.R302Q,ENST00000402010,NM_001039469.2,c.905G>A,MODERATE,YES,deleterious(0),possibly_damaging(0.606),1;MARK2,missense_variant,p.R302Q,ENST00000361128,NM_001163296.2,c.905G>A,MODERATE,,deleterious(0.01),probably_damaging(0.978),1;MARK2,missense_variant,p.R302Q,ENST00000508192,NM_004954.5,c.905G>A,MODERATE,,deleterious(0.01),benign(0.151),1;MARK2,missense_variant,p.R302Q,ENST00000350490,NM_001163297.2,c.905G>A,MODERATE,,deleterious(0.01),benign(0.098),1;MARK2,missense_variant,p.R302Q,ENST00000502399,,c.905G>A,MODERATE,,deleterious(0),possibly_damaging(0.905),1;MARK2,missense_variant,p.R269Q,ENST00000509502,NM_017490.4,c.806G>A,MODERATE,,deleterious(0.01),benign(0.238),1;MARK2,missense_variant,p.R302Q,ENST00000513765,,c.905G>A,MODERATE,,deleterious(0),possibly_damaging(0.471),1;MARK2,missense_variant,p.R302Q,ENST00000679216,,c.905G>A,MODERATE,,deleterious(0.01),probably_damaging(0.969),1;MARK2,missense_variant,p.R302Q,ENST00000425897,,c.905G>A,MODERATE,,deleterious(0.01),probably_damaging(0.959),1;MARK2,missense_variant,p.R269Q,ENST00000408948,,c.806G>A,MODERATE,,deleterious(0.01),benign(0.238),1;MARK2,downstream_gene_variant,,ENST00000540169,,,MODIFIER,,,,1;MARK2,downstream_gene_variant,,ENST00000543220,,,MODIFIER,,,,1;MARK2,missense_variant,p.R269Q,ENST00000677688,,c.806G>A,MODERATE,,deleterious(0),probably_damaging(0.939),1;MARK2,non_coding_transcript_exon_variant,,ENST00000676602,,n.3744G>A,MODIFIER,,,,1;MARK2,non_coding_transcript_exon_variant,,ENST00000678482,,n.3315G>A,MODIFIER,,,,1;MARK2,non_coding_transcript_exon_variant,,ENST00000679321,,n.1588G>A,MODIFIER,,,,1;MARK2,non_coding_transcript_exon_variant,,ENST00000678662,,n.762G>A,MODIFIER,,,,1;MARK2,upstream_gene_variant,,ENST00000535116,,,MODIFIER,,,,1;MARK2,upstream_gene_variant,,ENST00000677303,,,MODIFIER,,,,1;MARK2,downstream_gene_variant,,ENST00000679213,,,MODIFIER,,,,1\tA\tENSG00000072518\tENST00000402010\tTranscript\tmissense_variant\tmissense_variant\t1484/3300\t905/2367\t302/788\tR/Q\tcGa/cAa\trs199684279\t\t1\tMARK2\tHGNC\tHGNC:3332\tprotein_coding\tYES\tCCDS53649.1\tENSP00000385751\tQ7KZI7.169\t\tUPI00004F6F00\tQ7KZI7-1\tNM_001039469.2\t\tA1\t\tdeleterious(0)\tpossibly_damaging(0.606)\t10/19\t\tPDB-ENSP_mappings:3iec.A;PDB-ENSP_mappings:3iec.B;PDB-ENSP_mappings:3iec.C;PDB-ENSP_mappings:3iec.D;PDB-ENSP_mappings:5eak.A;PDB-ENSP_mappings:5eak.B;PDB-ENSP_mappings:5kz7.A;PDB-ENSP_mappings:5kz7.B;PDB-ENSP_mappings:5kz8.A;PDB-ENSP_mappings:5kz8.B;PROSITE_profiles:PS50011;CDD:cd14072;PANTHER:PTHR24346:SF56;PANTHER:PTHR24346;Gene3D:1.10.510.10;Pfam:PF00069;SMART:SM00220;Superfamily:SSF56112\t\t\t\t\t\t\t0.0002272\t0.0\t1.591e-05\t6.152e-05\t0.0\t0.0\t0.0\t0.0\t2.637e-05\t0.0\t0.0\t0.0002272\tAA\t2.0287299776100554e-05\t0.0\t0.0\t0.0\t0.0\t0.0\t0.0\t0.0\t4.6302000555442646e-05\t0.0\t0.0\t4.6302000555442646e-05\tnfe\t\t\t\t\t\t\t\t\t\tMODERATE\t1\tSNV\t1\t\t\t\tAGATCGATGGA\tf74293a0-f4b4-49da-937f-db43c68d9062\ta7447bac-36b2-44c3-86a0-6e52a550ef34\tf89588e9-ca73-4465-a7fb-7246edb45e3a\t\t\tN\tUnknown\t\t\t\tmutect2;varscan2\n', 'KDM2A\t22992\tWUGSC\tGRCh38\tchr11\t67250119\t67250119\t+\tMissense_Mutation\tSNP\tG\tG\tA\t\t\tTCGA-XX-A899-01A-11D-A36J-09\tTCGA-XX-A899-10A-01D-A36M-09\t\t\t\t\t\t\t\t\tSomatic\t\t\t\t\t\t\t49fb101d-f242-4abf-bf85-6a8c3ced711d\t0ffd9ad1-6643-42ff-af29-13389bfb1364\tc.2089G>A\tp.Val697Met\tp.V697M\tENST00000529006\t17/21\t113\t101\t12\t123\t\t\tKDM2A,missense_variant,p.V697M,ENST00000529006,NM_012308.3,c.2089G>A,MODERATE,YES,tolerated(0.22),benign(0.06),1;KDM2A,missense_variant,p.V697M,ENST00000398645,,c.2089G>A,MODERATE,,tolerated(0.11),possibly_damaging(0.648),1;KDM2A,missense_variant,p.V680M,ENST00000308783,,c.2038G>A,MODERATE,,tolerated(0.22),benign(0.06),1;KDM2A,missense_variant,p.V258M,ENST00000530342,NM_001256405.2,c.772G>A,MODERATE,,tolerated(0.17),possibly_damaging(0.446),1;KDM2A,non_coding_transcript_exon_variant,,ENST00000526258,,n.1665G>A,MODIFIER,,,,1;KDM2A,non_coding_transcript_exon_variant,,ENST00000531696,,n.1441G>A,MODIFIER,,,,1;KDM2A,upstream_gene_variant,,ENST00000524657,,,MODIFIER,,,,1;KDM2A,downstream_gene_variant,,ENST00000525041,,,MODIFIER,,,,1;KDM2A,downstream_gene_variant,,ENST00000529124,,,MODIFIER,,,,1;KDM2A,downstream_gene_variant,,ENST00000534486,,,MODIFIER,,,,1;AP001885.3,downstream_gene_variant,,ENST00000652902,,,MODIFIER,YES,,,-1\tA\tENSG00000173120\tENST00000529006\tTranscript\tmissense_variant\tmissense_variant\t2959/7386\t2089/3489\t697/1162\tV/M\tGtg/Atg\tCOSV100445428\t\t1\tKDM2A\tHGNC\tHGNC:13606\tprotein_coding\tYES\tCCDS44657.1\tENSP00000432786\tQ9Y2K7.185\tI3VM53.76\tUPI00001678A9\tQ9Y2K7-1\tNM_012308.3\tNM_012308.3\tP1\t\ttolerated(0.22)\tbenign(0.06)\t17/21\t\tPANTHER:PTHR23123:SF3;PANTHER:PTHR23123\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t1\t\t\t\t\t\t\t\tMODERATE\t1\tSNV\t1\t\t1\t\tAAGCTGTGCAA\tf74293a0-f4b4-49da-937f-db43c68d9062\ta7447bac-36b2-44c3-86a0-6e52a550ef34\tf89588e9-ca73-4465-a7fb-7246edb45e3a\t\t\tN\tUnknown\t\t\t\tmuse;mutect2;varscan2\n', 'C2CD3\t26005\tWUGSC\tGRCh38\tchr11\t74078638\t74078638\t+\tSilent\tSNP\tC\tC\tT\t\t\tTCGA-XX-A899-01A-11D-A36J-09\tTCGA-XX-A899-10A-01D-A36M-09\t\t\t\t\t\t\t\t\tSomatic\t\t\t\t\t\t\t49fb101d-f242-4abf-bf85-6a8c3ced711d\t0ffd9ad1-6643-42ff-af29-13389bfb1364\tc.4080G>A\tp.Val1360=\tp.V1360=\tENST00000334126\t23/33\t73\t64\t9\t24\t\t\tC2CD3,synonymous_variant,p.V1360=,ENST00000334126,NM_001286577.2,c.4080G>A,LOW,YES,,,-1;C2CD3,sy

In [4]:
import pandas as pd

def analyze_tsv_file(file_path):
    df = pd.read_csv(file_path, sep='\t', nrows=10)
    print(f"First 10 rows of {file_path}:")
    print(df)

# Example usage
tsv_file_path = 'data_tcga/tcga(sean)/mrna_expression_data/515f8866-8744-44d8-9e4b-0e734d0c201b/c5d73777-b7f3-4107-9efc-afde92f70469.rna_seq.augmented_star_gene_counts.tsv'
analyze_tsv_file(tsv_file_path)

First 10 rows of data_tcga/tcga(sean)/mrna_expression_data/515f8866-8744-44d8-9e4b-0e734d0c201b/c5d73777-b7f3-4107-9efc-afde92f70469.rna_seq.augmented_star_gene_counts.tsv:
                                                                                                                     # gene-model: GENCODE v36
gene_id            gene_name gene_type      unstranded stranded_first stranded_second tpm_unstranded fpkm_unstranded        fpkm_uq_unstranded
N_unmapped         NaN       NaN            2476851    2476851        2476851         NaN            NaN                                   NaN
N_multimapping     NaN       NaN            4572009    4572009        4572009         NaN            NaN                                   NaN
N_noFeature        NaN       NaN            2235792    24766058       24872173        NaN            NaN                                   NaN
N_ambiguous        NaN       NaN            5388767    1252536        1243009         NaN            NaN                                   NaN
ENSG00000000003.15 TSPAN6    protein_coding 1316       655            661             22.6458        7.0228                             7.0292
ENSG00000000005.6  TNMD      protein_coding 3          2              1               0.1587         0.0492                             0.0492
ENSG00000000419.13 DPM1      protein_coding 1703       862            841             110.1318       34.1535                           34.1847
ENSG00000000457.14 SCYL3     protein_coding 765        752            748             8.6754         2.6904                             2.6928
ENSG00000000460.17 C1orf112  protein_coding 521        620            673             6.8119         2.1125                             2.1144